### PR TITLE
Introduce matcher for struct of a given type

### PR DESCRIPTION
**Pull request by joshrieken**
I'm not sure whether this is the best way to implement this, but I wanted to at least start the conversation.

### CODE REVIEW

**Comment by joshrieken** [comment]
Alternatively, we could make it work like this:

```
assert_called MyModule.my_function(ElixirMock.Matchers.any(%Person{}))
```

It's a little cleaner, but breaks the convention of explicitly specifying the type via atom, and therefore might be less clear.

**Comment by wanderanimrod** [comment]
Thanks again @facto .

I think I like `Matchers.any(%Person{})` much better. It fits in better with the `Matchers.any(:int)` and `Matchers.any(:atom)` if you think about structs as types. Furthermore, the use of `any` together with the struct syntax `%Person{}` is explicit enough. Do you mind making that change to your PR and docs?

**Comment by joshrieken** [comment]
@wanderanimrod I like it a lot better too now that I've had time to think about it. Changes have been made.

**Comment by wanderanimrod** [comment]
@facto , this has been released in version [0.2.7](https://github.com/wanderanimrod/elixir_mock/releases/tag/0.2.7). Thanks.

**Pull request merged**
